site_name: cubao
site_url: https://cubao.readthedocs.io
site_description: cubao index page
site_author: district10

repo_url: https://github.com/cubao/index
edit_uri: blob/master/docs/

theme: readthedocs
nav:
    -   Home: index.md
    -   Notebooks:
        -   notebooks/index.md
        -   notebooks/concave-hull.ipynb
        -   notebooks/polyline-ruler.ipynb
    -   About:
        -   Release Notes: about/release-notes.md
        -   License: about/license.md

plugins:
-   include-markdown
-   mkdocs-jupyter

copyright: Copyright &copy; 2023 <a href="https://github.com/cubao">cubao team</a>.
